# Generated by Django 4.2 on 2023-05-07 13:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(default='Topic Name', max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Webpage Name', max_length=50, unique=True)),
                ('url', models.URLField(default='https://www.webpage.com', unique=True)),
                ('topic', models.ForeignKey(default='Topic Name', on_delete=django.db.models.deletion.CASCADE, to='first_app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.ForeignKey(default='Webpage name', on_delete=django.db.models.deletion.CASCADE, to='first_app.webpage')),
            ],
        ),
    ]
